/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author MMMM
 */
public class ListarAluno extends javax.swing.JFrame {

    /**
     * Creates new form ListarAluno
     */
    public ListarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscaAlunoRadio = new javax.swing.JRadioButton();
        codigoAluno = new javax.swing.JTextField();
        listaAlunoRadio = new javax.swing.JRadioButton();
        buscaBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        jLabel1.setText("Listar Alunos");

        buscaAlunoRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaAlunoRadio.setText("Buscar aluno");
        buscaAlunoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaAlunoRadioActionPerformed(evt);
            }
        });

        codigoAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Código do Aluno"));

        listaAlunoRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaAlunoRadio.setText("Listar todos");
        listaAlunoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlunoRadioActionPerformed(evt);
            }
        });

        buscaBotao.setText("Busca");
        buscaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscaAlunoRadio)
                        .addGap(69, 69, 69)
                        .addComponent(codigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(listaAlunoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaAlunoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaAlunoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(buscaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaAlunoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaAlunoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaAlunoRadioActionPerformed

    private void listaAlunoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlunoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAlunoRadioActionPerformed

    private void buscaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBotaoActionPerformed
       
    }//GEN-LAST:event_buscaBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buscaAlunoRadio;
    private javax.swing.JButton buscaBotao;
    private javax.swing.JTextField codigoAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton listaAlunoRadio;
    // End of variables declaration//GEN-END:variables
}
